#!/usr/bin/env python
"""This file is automatically generated by generate_version_info
It uses the current working tree to determine the revision.
So don't edit it. :)
"""

version_info = {'branch_nick': u'zim-trunk',
 'build_date': '2014-09-30 21:19:45 +0200',
 'clean': None,
 'date': '2014-09-30 21:17:15 +0200',
 'revision_id': 'jaap.karssenberg@gmail.com-20140930191715-hpl66psh7yudcskr',
 'revno': '738'}

revisions = {}

file_revisions = {}


if __name__ == '__main__':
    print 'revision: %(revno)s' % version_info
    print 'nick: %(branch_nick)s' % version_info
    print 'revision id: %(revision_id)s' % version_info
